version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: msme_rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: msme_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msme
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - msme_postgres_data_v3:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  rabbitmq_data:
  msme_postgres_data_v3:
